title: Configuring Kubernetes kubectl
tagline: A brand new course on Learning Lab
description: >-
  This course leads the student through the steps necessary to use the
  Kubernetes kubectl command from within an Actions workflow.
template:
  repo: configuring-kubernetes-kubectl-template
  name: configuring-kubernetes-kubectl
before:
  - type: createIssue
    title: Welcome!
    body: welcome.md
steps:
  - title: Welcome!
    description: Please review this issue.
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
    - type: createIssue
      action_id: intro_issue
      title: A Brief Review of Containerization
      body: introduction-and-review.md
    - type: respond
      with: go-to-issue.md
      data:
        issueURL: '%actions.intro_issue.data.html_url%'

  - title: Review of Containerization
    description: Preparing workloads for Kubernetes
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
    - type: createIssue
      action_id: encrypt_issue
      title: Encrypting the KUBECONFIG File
      body: encrypt.md  
  - title: Review of Containerization
    description: Preparing workloads for Kubernetes
    event: issues.closed
    link: '{{ repoUrl }}/issues/3'
    actions:
    - type: createIssue
      action_id: encrypt_issue
      title: Encrypting the KUBECONFIG File
      body: decrypt.md  
